### ISSUE TITLE
[feat] make slider draggable

### ISSUE THREAD

**Issue by hyundonny** [hyundonny/ncnc-app#3]
# TASK CARD

Task Description : get rid of slider scrollbar, make it draggable instead

Date : 2022-02-28

## to-do

- [x] get rid of slider scrollbar
- [x] make onMouseDown, onMouseMove, onMouseUp, onMouseLeave handlers for slider
- [x] use scrollIntoView to scroll active slider item into view
