### ISSUE TITLE
[modify] get rid of brand component

### ISSUE THREAD

**Issue by hyundonny** [hyundonny/ncnc-app#4]
# TASK CARD

Task Description : get rid of brand component, because it's really more of a page

Date : 2022-03-01

## to-do

- [x] delete brand component
- [x] move slider and grid into the categories page
- [x] rename props, types from 'brands' to 'categories'
