### ISSUE TITLE
[modify] remove main component

### ISSUE THREAD

**Issue by hyundonny** [hyundonny/ncnc-app#5]
# TASK CARD

Task Description : remove main component, it's supposed to be a page not a component

Date : 2022-03-02

## to-do

- [ ] move carousel component out of main folder and into component folder
- [ ] move main components contents into pages/index.tsx
- [ ] remove unnecessary code, fix styles of pages/index.tsx
