### ISSUE TITLE
[modify] create WarningItem component

### ISSUE THREAD

**Issue by hyundonny** [hyundonny/ncnc-app#8]
# TASK CARD

Task Description : create WarningItem component and util function (modifyWarning)

Date : 2022-03-02

## to-do

- [ ] create modifyWarning to parse and modify given warning string
- [ ] create WarningItem component
- [ ] move WarningItem component and ItemBox component from item-detail component to items/[id] page
